---
# Include OS specific variables
- ansible.builtin.include_tasks: variables.yml

- ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_distribution == 'Debian'

- ansible.builtin.include_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- ansible.builtin.include_tasks: install-composer.yml
  when: php_install_composer|bool

- name: Generate FPM pool config
  include_tasks: generate-fpm-config-pool.yml
  loop: "{{ php_pools }}"
  loop_control:
    loop_var: php_pool
  when: php_pools is defined and php_pools | length > 0