---
- ansible.builtin.include_tasks: variables.yml

- ansible.builtin.include_tasks: setup-debian.yml
  when: ansible_distribution == 'Debian'

- ansible.builtin.include_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- ansible.builtin.include_tasks: install-composer.yml
  when: php_install_composer|bool