---
- name: Install dependency package before installing Sury's repo
  ansible.builtin.apt:
    pkg:
      - gpg
      - apt-transport-https
      - lsb-release
      - ca-certificates
    state: present
    update_cache: yes

- name: Add Sury's APT key
  ansible.builtin.apt_key: 
    url: https://packages.sury.org/php/apt.gpg
    state: present  

- name: Add Sury's APT repository
  ansible.builtin.apt_repository: 
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present

- name: Install extensions for each selected PHP version
  include_tasks: debian-install-php-extensions.yml
  loop: "{{ php_install_versions }}"
  loop_control:
    loop_var: php_version